# DAY-1

In [12]:
name="Pranesh"

In [7]:
print(name)

Pranesh


In [13]:
type(name)

str

In [17]:
age=input("Enter the age:")

Enter the age:Pranesh


In [18]:
age.isnumeric()

False

In [27]:
a=10
b=3
c=a/b
d=a//b
print (c,type(c))


3.3333333333333335 <class 'float'>


In [29]:
print(d,type(d))

3 <class 'int'>


In [33]:
a=0
if a>0:
    print("a is Positive")
elif a==0:
    print("a is zero")
else:
    print("a is Negative")

a is zero


In [40]:
a=int(input("Enter the no :"))
if a%2==0:
    print("a is even")
else:
    print("a is odd")

Enter the no :13
a is odd


In [51]:
for i in range(1,50,2):
        print(i,end=",")

1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,

In [57]:
for i in range(1,15):
    if i%3!=0:
        print(i,end=",")

1,2,4,5,7,8,10,11,13,14,

In [60]:
for i in range(1,14,2):
    print(i/10,end=",")

0.1,0.3,0.5,0.7,0.9,1.1,1.3,

In [73]:
for i in range(1,6):
    if i%2==0:
        print("False",end=',')
    else:
        print("True",end=",")
        
#another method
for i in range(1,5):
    print(i%3==0,end=',')
    


True,False,True,False,True,False,False,True,False,False,

In [1]:
#another method
for i in range(1,5):
    print(i%3==0,end=',')

False,False,True,False,

In [74]:
name="Pranesh"
for i in name:
    if i.lower() in 'aeiou':
        print(i)

a
e


In [90]:
string="a9b22f56g"
for i in string:
    if i.isalpha():
        print(i,end=",")
    
    

a,b,f,g,

In [94]:
for i in range(10,0,-1):
    print (i,end=",")

10,9,8,7,6,5,4,3,2,1,

In [97]:
for i in range(50,0,-1):
    print (i,end=",")

50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,

In [102]:
for i in range(1,6):
    print("*"*i)

*
**
***
****
*****


In [111]:
for i in range(5,0,-1):
    print("*"*i)

*****
****
***
**
*


In [114]:
for i in range(5,0,-1):
    print(" "*(5-i)+"*"*i)

*****
 ****
  ***
   **
    *


In [115]:
for i in range (1,6):
     print(" "*(5-i)+"* "*i)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [143]:
for i,j in zip(range(4,-1,-1),range(1,10,2)):
     print(" "*i+"*"*j) 

    *
   ***
  *****
 *******
*********


In [110]:
for i in range (1,6):
    print(" "*(6-i)+"*"*i)

     *
    **
   ***
  ****
 *****


In [146]:
str1="Good Morning"
print(str1[0:5])

Good 


In [150]:
print(str1[0:5:2])

Go 


In [156]:
print(str1[-5:])

rning


In [164]:
print(str1[3::-1])

dooG


In [166]:
print(str1[-1::-1])

gninroM dooG


In [174]:
a=input("Enter the string :").lower()
if a==a[-1::-1]:
    print("It is a palindrome")
else:
    print("It is not a palindrome")

Enter the string :Rotor
It is a palindrome


In [176]:
s1="Hello! Welcome to Sep 2023 batch"
for i in s1:
    if i.isupper():
        print(i)

H
W
S


In [194]:
count=0
for i in s1:
    if i.isupper():
        count=count+1
print(count)

3


In [196]:
l1=[]

In [197]:
l1.append(1)
l1.append(2)
l1.append(3)

In [198]:
print(l1)

[1, 2, 3]


In [210]:
l_2=[4,5,6,9]

In [211]:
l1.extend(l_2)

In [212]:
print(l1)

[3, 5, 4, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 4, 5, 6, 9]


In [217]:
l1.remove(5)
print(l1)

[4, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 4, 5, 6, 9]


In [218]:
l1.insert(2,5)
print(l1)

[4, 5, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 4, 5, 6, 9]


In [219]:
l1.pop()

9

In [220]:
print(l1)

[4, 5, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 4, 5, 6]


In [221]:
l1.pop(0)

4

In [222]:
print(l1)

[5, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 4, 5, 6]


In [227]:
s2="Hello! Welcome to this python course"

In [228]:
l3=list(s2)
print(l3)#character wise (string to list)

['H', 'e', 'l', 'l', 'o', '!', ' ', 'W', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 't', 'h', 'i', 's', ' ', 'p', 'y', 't', 'h', 'o', 'n', ' ', 'c', 'o', 'u', 'r', 's', 'e']


In [229]:
print(len(l1))

14


In [231]:
l4=s2.split(' ')#to convert string to list
print(l4)

['Hello!', 'Welcome', 'to', 'this', 'python', 'course']


In [233]:
" ".join(l4)#to convert list to string

'Hello! Welcome to this python course'

In [2]:
l_1=[1,5,3,9,21,4,63,22,7,14]   #list comphrension
l_2=[i for i in l_1 if i%2==0]

In [238]:
print(l_2)

[4, 22, 14]


In [243]:
l_3=[i*5 for i in l_1]
print(l_3)

[5, 25, 15, 45, 105, 20, 315, 110, 35, 70]


In [257]:
l_1=[1,5,3,9,21,4,63,22,7,14]

In [262]:
l1_even=[i for i in l_1 if i%2==0]
l1__odd=[i for i in l_1 if i%2!=0]
print(l1_even,l1__odd)

[4, 22, 14] [1, 5, 3, 9, 21, 63, 7]


In [247]:
above_10=[i for i in l_1 if i>10]
print (above_10)

[21, 63, 22, 14]


In [2]:
string_2="I wish everyone a happy and joyful weekend"


In [3]:
new_list=[i for i in string_2.split() if i[0] in "aeiouAEIOU" ]

In [4]:
print(new_list)

['I', 'everyone', 'a', 'and']


In [ ]:
l_1=[1,5,3,9,21,4,63,22,7,14]

In [7]:
l3=[i if i%2==0 else i*i for i in range(1,6)]
print(l3)

[1, 2, 9, 4, 25]


In [276]:
list_2=[i if i%2==0 else i*i for i in l_1]
print(list_2)

[1, 25, 9, 81, 441, 4, 3969, 22, 49, 14]


In [278]:
string_2="I wish everyone a happy and joyful weekend"

In [281]:
four_letters=[i.upper() if len(i)>4 else i for i in string_2.split()]
print(four_letters)

['I', 'wish', 'EVERYONE', 'a', 'HAPPY', 'and', 'JOYFUL', 'WEEKEND']


In [287]:
n=[i for i in range(2,101,2)]
print(n)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [6]:
l1=[1,2,4,6,7]
l2=(4,32,7,4,2)
l3=[i+j for i,j in zip(l1,l2)]
print(l3)

[5, 34, 11, 10, 9]


In [7]:
t1=tuple(zip(l1,l2))
print(t1)

((1, 4), (2, 32), (4, 7), (6, 4), (7, 2))


In [305]:
l4=[(i,j) for i,j in zip(l1,l2)]
print(l4)

[(1, 4), (2, 32), (4, 7), (6, 4), (7, 2)]


In [312]:
common_eleme=[i for i in l1 if i in l2]

In [316]:
print(common_eleme)

[2, 4, 7]


In [318]:
#lambda functions
square=lambda x:x**2
print(square(5))

25


In [14]:
add=lambda a,b:a+b
print(add(10,5))

15


In [ ]:
mul=lambda x:x*2
print(square(5))

In [12]:
#map--->no of elements in input=no of elements in o/p
l_1=[1,5,3,9,21,4,63,22,7,14]
map_1=list(map(lambda x:x*3,l_1))
print(map_1)

[3, 15, 9, 27, 63, 12, 189, 66, 21, 42]


In [324]:
string_2="I wish everyone a happy and joyful weekend"
l_2=string_2.split()

In [326]:
map_2=list(map(lambda x:x.upper(),l_2))  #with map
print(map_2)

['I', 'WISH', 'EVERYONE', 'A', 'HAPPY', 'AND', 'JOYFUL', 'WEEKEND']


In [331]:
map_2a=[i.upper() for i in l_2]#Without map
print(map_2a)

['I', 'WISH', 'EVERYONE', 'A', 'HAPPY', 'AND', 'JOYFUL', 'WEEKEND']


In [332]:
l1=[1,2,4,6,7]
l2=(4,32,7,4,2)
map_3=list(map(lambda x,y:x+y,l1,l2))
print(map_3)

[5, 34, 11, 10, 9]


In [15]:
l1=[1,2,4,6,7]
l2=(4,32,7,4,2)
map_4=list(map(lambda x,y:(x,y),l1,l2))
print(map_4)

[(1, 4), (2, 32), (4, 7), (6, 4), (7, 2)]


In [ ]:
#Filter -->to filter certain value based on given condition
#(i/p elements > o/p elements)

In [335]:
l_1=[1,5,3,9,21,4,63,22,7,14]
ftr_1=list(filter(lambda x:x%2!=0,l_1))
#ftr_ 1=[i for i in l_1 if i%2!=0]
print(ftr_1)

[1, 5, 3, 9, 21, 63, 7]


In [ ]:
#reduce-->output value-->1

In [336]:
from functools import reduce #To inport reduce function

In [337]:
l_1=[1,5,3,9,21,4,63,22,7,14]
rde_1=reduce(lambda x,y:x if x>y else y,l_1)
print(rde_1)

63


In [338]:
rde_2=reduce(lambda x,y:x+y,l_1)
print(rde_2)

149


In [340]:
l1=[1,2,2,3,2,1,4,4,5]
print(list(set(l1)))

[1, 2, 3, 4, 5]


In [342]:
set1={1,2,3}
set2={2,4,6}
set1.intersection(set2)#common elements

{2}

In [343]:
set1.union(set2)#all the elements

{1, 2, 3, 4, 6}

In [344]:
set1.difference(set2)#To print the set1 values those are not in set2

{1, 3}

In [345]:
#NUMPY ARRAY

In [1]:
import numpy as np  #To inport NUMPY ARRAY

In [ ]:
l1=[1,2,2,3,2,1,4,4,5]

In [352]:
arr=np.array(l1)
arr.reshape(3,3)

array([[1, 2, 2],
       [3, 2, 1],
       [4, 4, 5]])

In [356]:
arr=np.arange(1,11)
print(arr*3)

[ 3  6  9 12 15 18 21 24 27 30]


In [358]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,8,5,5])
arr1+arr2

array([ 5,  7, 11,  9, 10])

In [359]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,8,5,5])
(arr1+arr2)/2

array([2.5, 3.5, 5.5, 4.5, 5. ])

# DAY-2

In [ ]:
#NUMPY ARRAY

In [6]:
np.arange(1,9).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
np.repeat(1,9).reshape(3,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr=np.zeros(9)
arr[0::4]=1

In [17]:
arr.reshape((3,3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.array([[1 if i==j else 0 for j in range(3)]for i in range(3)])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
arr=np.zeros(9,dtype=int)
arr[0::2]=1
arr.reshape(3,3)

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [27]:
np.array([[i+1 for j in range(4)]for i in range(4)])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [28]:
arr=np.repeat(1,4)
np.vstack([arr,arr*2,arr*3,arr*4])

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [35]:
arr=np.ones((4,4),dtype=int)
arr[1:3,1:3]=0
arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [36]:
arr=np.ones((5,5),dtype=int)*5
arr[1:4,1:4]=0
arr

array([[5, 5, 5, 5, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 0, 0, 0, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
#Dictionary

In [38]:
dict1={"name":"Raj","Age":27,"Degree":"B.A"}
print(dict1)

{'name': 'Raj', 'Age': 27, 'Degree': 'B.A'}


In [41]:
dict1["salary"]=20000
print(dict1)

{'name': 'Raj', 'Age': 27, 'Degree': 'B.A', 'salary': 20000}


In [53]:
for i in dict1.values():
    print(i,end=" ")

Raj 30 B.A 20000 30 Pune 

In [55]:
print(list(dict1.values()))

['Raj', 30, 'B.A', 20000, 30, 'Pune']


In [48]:
dict1["Age"]=30
print(dict1)

{'name': 'Raj', 'Age': 30, 'Degree': 'B.A', 'salary': 20000, 'age': 30}


In [56]:
dict1["location"]="Pune"
(dict1)

{'name': 'Raj',
 'Age': 30,
 'Degree': 'B.A',
 'salary': 20000,
 'age': 30,
 'location': 'Pune'}

In [59]:
for key,value in dict1.items():
    print(key ,"is", value,end=",")

name is Raj,Age is 30,Degree is B.A,salary is 20000,age is 30,location is Pune,

In [69]:
del(dict1["location"])

KeyError: 'location'

In [68]:
dict1

{'name': 'Raj', 'Age': 30, 'Degree': 'B.A', 'salary': 20000, 'age': 30}

In [ ]:
#dictionary comprehension

In [70]:
d1={i:i*i for i in range(1,6)}
d1

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [71]:
l1=['Name','Age','Salary']
l2=['Raj',28,30000]

In [77]:
d2={i:j for i,j in zip(l1,l2)}
d2

{'Name': 'Raj', 'Age': 28, 'Salary': 30000}

In [78]:
d3={i:i**3 for i in range(1,6)}
d3

{1: 1, 2: 8, 3: 27, 4: 64, 5: 125}

In [80]:
l1=[1,2,3,6,7]
l2=[2,2,3,6,2,1]

In [81]:
d4={i:j for i,j in zip(l1,l2)}
d4

{1: 2, 2: 2, 3: 3, 6: 6, 7: 2}

In [88]:
l3=['My','Age','is','twenty','two']

In [109]:
d5={i:i[0] in 'aeiouAEIOU' for i in l3}
d5

{'My': False, 'Age': True, 'is': True, 'twenty': False, 'two': False}

In [113]:
d6={i:len(i) for i in l3}
d6

{'My': 2, 'Age': 3, 'is': 2, 'twenty': 6, 'two': 3}

In [115]:
#Data Frame

In [1]:
import pandas as pd

In [2]:
data={'subject':['english','maths','science','Arts'],
'marks':[80,75,91,84]}

In [3]:
df1=pd.DataFrame(data)
df1

subject  marks
0  english     80
1    maths     75
2  science     91
3     Arts     84

In [127]:
df1['marks'].sum()

330

In [129]:
df1['marks'].mean()

82.5

In [131]:
df1['marks'].median()

82.0

In [132]:
df1['marks'].count()

4

In [136]:
df1[df1['marks']>80]

subject  marks
2  science     91
3     Arts     84

In [137]:
df1[(df1['marks']>=70) & (df1['marks']<=85)]

subject  marks
0  english     80
1    maths     75
3     Arts     84

In [20]:
df1

subject  marks
0  english     80
1    maths     75
2  science     91
3     Arts     84

In [25]:
df1.loc[2:2]

subject  marks
2  science     91

In [30]:
df=pd.read_excel('People+Attrition.xlsx')

In [33]:
df.head()

S.No.  Gender              Department                JobRole MaritalStatus  \
0      1  Female                   Sales        Sales Executive        Single   
1      2    Male  Research & Development     Research Scientist       Married   
2      4    Male  Research & Development  Laboratory Technician        Single   
3      5  Female  Research & Development     Research Scientist       Married   
4      7    Male  Research & Development  Laboratory Technician       Married   

   JobSatisfaction  HourlyRate  MonthlyIncome  PercentSalaryHike  \
0                4        94.0           5993                 11   
1                2        61.0           5130                 23   
2                3        92.0           2090                 15   
3                3        56.0           2909                 11   
4                2        40.0           3468                 12   

   PerformanceRating  TotalWorkingYears  EnvironmentRating  YearsAtCompany  \
0                3.0                  8                  1               6   
1                4.0                 10                  3              10   
2                3.0                  7                  3               0   
3                3.0                  8                  3               8   
4                3.0                  6                  3               2   

   YearsInCurrentRole  Age  DistanceFromHome  YearsWithCurrManager Attrition  
0                   4   41                 1                     5       Yes  
1                   7   49                 8                     7        No  
2                   0   37                 2                     0       Yes  
3                   7   33                 3                     0        No  
4                   2   27                 2                     2        No

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   S.No.                 1470 non-null   int64  
 1   Gender                1470 non-null   object 
 2   Department            1470 non-null   object 
 3   JobRole               1470 non-null   object 
 4   MaritalStatus         1470 non-null   object 
 5   JobSatisfaction       1470 non-null   int64  
 6   HourlyRate            1469 non-null   float64
 7   MonthlyIncome         1470 non-null   int64  
 8   PercentSalaryHike     1470 non-null   int64  
 9   PerformanceRating     1469 non-null   float64
 10  TotalWorkingYears     1470 non-null   int64  
 11  EnvironmentRating     1470 non-null   int64  
 12  YearsAtCompany        1470 non-null   int64  
 13  YearsInCurrentRole    1470 non-null   int64  
 14  Age                   1470 non-null   int64  
 15  DistanceFromHome     

In [153]:
df.dtypes

S.No.                     int64
Gender                   object
Department               object
JobRole                  object
MaritalStatus            object
JobSatisfaction           int64
HourlyRate              float64
MonthlyIncome             int64
PercentSalaryHike         int64
PerformanceRating       float64
TotalWorkingYears         int64
EnvironmentRating         int64
YearsAtCompany            int64
YearsInCurrentRole        int64
Age                       int64
DistanceFromHome          int64
YearsWithCurrManager      int64
Attrition                object
dtype: object

In [35]:
df.describe()

S.No.  JobSatisfaction   HourlyRate  MonthlyIncome  \
count  1470.000000      1470.000000  1469.000000    1470.000000   
mean   1024.865306         2.808163    65.886998    6502.931293   
std     602.024335         1.083292    20.335725    4707.956783   
min       1.000000         1.000000    30.000000    1009.000000   
25%     491.250000         2.000000    48.000000    2911.000000   
50%    1020.500000         3.000000    66.000000    4919.000000   
75%    1555.750000         4.000000    84.000000    8379.000000   
max    2068.000000         4.000000   100.000000   19999.000000   

       PercentSalaryHike  PerformanceRating  TotalWorkingYears  \
count        1470.000000        1469.000000        1470.000000   
mean           15.209524           3.153846          11.279592   
std             3.659938           0.360924           7.780782   
min            11.000000           3.000000           0.000000   
25%            12.000000           3.000000           6.000000   
50%            14.000000           3.000000          10.000000   
75%            18.000000           3.000000          15.000000   
max            25.000000           4.000000          40.000000   

       EnvironmentRating  YearsAtCompany  YearsInCurrentRole          Age  \
count        1470.000000     1470.000000         1470.000000  1470.000000   
mean            2.761224        7.008163            4.229252    36.923810   
std             0.706476        6.126525            3.623137     9.135373   
min             1.000000        0.000000            0.000000    18.000000   
25%             2.000000        3.000000            2.000000    30.000000   
50%             3.000000        5.000000            3.000000    36.000000   
75%             3.000000        9.000000            7.000000    43.000000   
max             4.000000       40.000000           18.000000    60.000000   

       DistanceFromHome  YearsWithCurrManager  
count       1470.000000           1470.000000  
mean           9.192517              4.123129  
std            8.106864              3.568136  
min            1.000000              0.000000  
25%            2.000000              2.000000  
50%            7.000000              3.000000  
75%           14.000000              7.000000  
max           29.000000             17.000000

In [36]:
df.describe(include='object')

Gender              Department          JobRole MaritalStatus Attrition
count    1470                    1470             1470          1470      1470
unique      2                       3                9             3         2
top      Male  Research & Development  Sales Executive       Married        No
freq      882                     961              326           673      1233

In [157]:
df.head()

S.No.  Gender              Department                JobRole MaritalStatus  \
0      1  Female                   Sales        Sales Executive        Single   
1      2    Male  Research & Development     Research Scientist       Married   
2      4    Male  Research & Development  Laboratory Technician        Single   
3      5  Female  Research & Development     Research Scientist       Married   
4      7    Male  Research & Development  Laboratory Technician       Married   

   JobSatisfaction  HourlyRate  MonthlyIncome  PercentSalaryHike  \
0                4        94.0           5993                 11   
1                2        61.0           5130                 23   
2                3        92.0           2090                 15   
3                3        56.0           2909                 11   
4                2        40.0           3468                 12   

   PerformanceRating  TotalWorkingYears  EnvironmentRating  YearsAtCompany  \
0                3.0                  8                  1               6   
1                4.0                 10                  3              10   
2                3.0                  7                  3               0   
3                3.0                  8                  3               8   
4                3.0                  6                  3               2   

   YearsInCurrentRole  Age  DistanceFromHome  YearsWithCurrManager Attrition  
0                   4   41                 1                     5       Yes  
1                   7   49                 8                     7        No  
2                   0   37                 2                     0       Yes  
3                   7   33                 3                     0        No  
4                   2   27                 2                     2        No

In [37]:
df_sales=df[df['Department']=='Sales']
df_sales

S.No.  Gender Department               JobRole MaritalStatus  \
0         1  Female      Sales       Sales Executive        Single   
18       23  Female      Sales               Manager       Married   
21       27    Male      Sales  Sales Representative        Single   
27       35    Male      Sales       Sales Executive       Married   
29       38  Female      Sales               Manager        Single   
...     ...     ...        ...                   ...           ...   
1454   2046  Female      Sales       Sales Executive        Single   
1461   2055    Male      Sales       Sales Executive      Divorced   
1462   2056  Female      Sales       Sales Executive       Married   
1464   2060  Female      Sales  Sales Representative        Single   
1468   2065    Male      Sales       Sales Executive       Married   

      JobSatisfaction  HourlyRate  MonthlyIncome  PercentSalaryHike  \
0                   4        94.0           5993                 11   
18                  4        78.0          15427                 16   
21                  1        82.0           3407                 23   
27                  2        48.0           6825                 11   
29                  4        83.0          18947                 12   
...               ...         ...            ...                ...   
1454                3        50.0           4850                 15   
1461                1        39.0          10854                 13   
1462                4        60.0          12031                 11   
1464                3        30.0           2966                 18   
1468                2        63.0           5390                 14   

      PerformanceRating  TotalWorkingYears  EnvironmentRating  YearsAtCompany  \
0                   3.0                  8                  1               6   
18                  3.0                 31                  3              25   
21                  4.0                 10                  3               5   
27                  3.0                 10                  3               9   
29                  3.0                 22                  2               2   
...                 ...                ...                ...             ...   
1454                3.0                  8                  3               5   
1461                3.0                 20                  3               3   
1462                3.0                 21                  2              20   
1464                3.0                  5                  3               4   
1468                3.0                 17                  2               9   

      YearsInCurrentRole  Age  DistanceFromHome  YearsWithCurrManager  \
0                      4   41                 1                     5   
18                     8   53                 2                     7   
21                     3   36                 9                     3   
27                     7   42                 8                     2   
29                     2   46                 2                     1   
...                  ...  ...               ...                   ...   
1454                   3   45                20                     1   
1461                   2   50                28                     0   
1462                   9   39                24                     6   
1464                   2   26                 5                     0   
1468                   6   49                 2                     8   

     Attrition  
0          Yes  
18          No  
21         Yes  
27          No  
29          No  
...        ...  
1454        No  
1461       Yes  
1462        No  
1464        No  
1468        No  

[446 rows x 18 columns]

In [174]:
df_female_single=df[(df['Gender']=='Female')&(df['MaritalStatus']=='Single')]
df_female_single

S.No.  Gender              Department                JobRole  \
0         1  Female                   Sales        Sales Executive   
11       15  Female  Research & Development  Laboratory Technician   
22       28  Female  Research & Development      Research Director   
26       33  Female  Research & Development     Research Scientist   
29       38  Female                   Sales                Manager   
...     ...     ...                     ...                    ...   
1426   2010  Female  Research & Development  Laboratory Technician   
1450   2040  Female         Human Resources        Human Resources   
1454   2046  Female                   Sales        Sales Executive   
1460   2054  Female  Research & Development     Research Scientist   
1464   2060  Female                   Sales   Sales Representative   

     MaritalStatus  JobSatisfaction  HourlyRate  MonthlyIncome  \
0           Single                4        94.0           5993   
11          Single                3        49.0           4193   
22          Single                2        53.0          11994   
26          Single                1        72.0           3919   
29          Single                4        83.0          18947   
...            ...              ...         ...            ...   
1426        Single                2        49.0           2837   
1450        Single                4        31.0           8837   
1454        Single                3        50.0           4850   
1460        Single                1        73.0           3785   
1464        Single                3        30.0           2966   

      PercentSalaryHike  PerformanceRating  TotalWorkingYears  \
0                    11                3.0                  8   
11                   12                3.0                 10   
22                   11                3.0                 13   
26                   22                4.0                 10   
29                   12                3.0                 22   
...                 ...                ...                ...   
1426                 13                3.0                  6   
1450                 16                3.0                  9   
1454                 15                3.0                  8   
1460                 14                3.0                  5   
1464                 18                3.0                  5   

      EnvironmentRating  YearsAtCompany  YearsInCurrentRole  Age  \
0                     1               6                   4   41   
11                    3               9                   5   29   
22                    3              12                   6   34   
26                    3              10                   2   32   
29                    2               2                   2   46   
...                 ...             ...                 ...  ...   
1426                  3               6                   2   32   
1450                  3               9                   0   35   
1454                  3               5                   3   45   
1460                  1               5                   4   29   
1464                  3               4                   2   26   

      DistanceFromHome  YearsWithCurrManager Attrition  
0                    1                     5       Yes  
11                  15                     8        No  
22                   7                    11        No  
26                  16                     7       Yes  
29                   2                     1        No  
...                ...                   ...       ...  
1426                29                     1        No  
1450                26                     7        No  
1454                20                     1        No  
1460                28                     4        No  
1464                 5                     0        No  

[199 rows x 18 columns]

In [177]:
df_mid=df[(df['Age']>=45 & (df['Age']<=35))]
df_mid

S.No.  Gender              Department                    JobRole  \
0         1  Female                   Sales            Sales Executive   
1         2    Male  Research & Development         Research Scientist   
2         4    Male  Research & Development      Laboratory Technician   
3         5  Female  Research & Development         Research Scientist   
4         7    Male  Research & Development      Laboratory Technician   
...     ...     ...                     ...                        ...   
1465   2061    Male  Research & Development      Laboratory Technician   
1466   2062    Male  Research & Development  Healthcare Representative   
1467   2064    Male  Research & Development     Manufacturing Director   
1468   2065    Male                   Sales            Sales Executive   
1469   2068    Male  Research & Development      Laboratory Technician   

     MaritalStatus  JobSatisfaction  HourlyRate  MonthlyIncome  \
0           Single                4        94.0           5993   
1          Married                2        61.0           5130   
2           Single                3        92.0           2090   
3          Married                3        56.0           2909   
4          Married                2        40.0           3468   
...            ...              ...         ...            ...   
1465       Married                4        41.0           2571   
1466       Married                1        42.0           9991   
1467       Married                2        87.0           6142   
1468       Married                2        63.0           5390   
1469       Married                3        82.0           4404   

      PercentSalaryHike  PerformanceRating  TotalWorkingYears  \
0                    11                3.0                  8   
1                    23                4.0                 10   
2                    15                3.0                  7   
3                    11                3.0                  8   
4                    12                3.0                  6   
...                 ...                ...                ...   
1465                 17                3.0                 17   
1466                 15                3.0                  9   
1467                 20                4.0                  6   
1468                 14                3.0                 17   
1469                 12                3.0                  6   

      EnvironmentRating  YearsAtCompany  YearsInCurrentRole  Age  \
0                     1               6                   4   41   
1                     3              10                   7   49   
2                     3               0                   0   37   
3                     3               8                   7   33   
4                     3               2                   2   27   
...                 ...             ...                 ...  ...   
1465                  3               5                   2   36   
1466                  3               7                   7   39   
1467                  3               6                   2   27   
1468                  2               9                   6   49   
1469                  4               4                   3   34   

      DistanceFromHome  YearsWithCurrManager Attrition  
0                    1                     5       Yes  
1                    8                     7        No  
2                    2                     0       Yes  
3                    3                     0        No  
4                    2                     2        No  
...                ...                   ...       ...  
1465                23                     3        No  
1466                 6                     7        No  
1467                 4                     3        No  
1468                 2                     8        No  
1469                 8                     2        No  

[1470 rows x 18 columns]

In [188]:
df_rich=df.sort_values(by=['MonthlyIncome'],ascending=False).head(10)
df_rich

S.No.  Gender              Department            JobRole MaritalStatus  \
190     259    Male  Research & Development            Manager       Married   
746    1035  Female  Research & Development  Research Director      Divorced   
851    1191  Female  Research & Development            Manager      Divorced   
165     226  Female  Research & Development            Manager        Single   
568     787    Male  Research & Development            Manager       Married   
918    1282    Male                   Sales            Manager      Divorced   
749    1038  Female                   Sales            Manager       Married   
1242   1740    Male                   Sales            Manager        Single   
898    1255    Male  Research & Development  Research Director       Married   
956    1338    Male         Human Resources            Manager        Single   

      JobSatisfaction  HourlyRate  MonthlyIncome  PercentSalaryHike  \
190                 3        65.0          19999                 14   
746                 3        55.0          19973                 22   
851                 1        92.0          19943                 13   
165                 2        53.0          19926                 15   
568                 1        78.0          19859                 13   
918                 2        83.0          19847                 24   
749                 4        57.0          19845                 15   
1242                2        88.0          19833                 14   
898                 4        96.0          19740                 14   
956                 2        99.0          19717                 14   

      PerformanceRating  TotalWorkingYears  EnvironmentRating  YearsAtCompany  \
190                 3.0                 34                  3              33   
746                 4.0                 21                  3              21   
851                 3.0                 28                  3               5   
165                 3.0                 21                  3               5   
568                 3.0                 24                  3               5   
918                 4.0                 31                  2              29   
749                 3.0                 33                  3              32   
1242                3.0                 21                  2              21   
898                 3.0                 25                  3               8   
956                 3.0                 36                  3               7   

      YearsInCurrentRole  Age  DistanceFromHome  YearsWithCurrManager  \
190                   18   52                 1                     9   
746                   16   41                 7                    10   
851                    2   56                 4                     2   
165                    4   50                11                     4   
568                    2   55                 2                     4   
918                   10   51                 9                    10   
749                   14   52                 2                     9   
1242                   8   40                 7                     8   
898                    7   43                 3                     7   
956                    3   56                 8                     7   

     Attrition  
190         No  
746         No  
851         No  
165         No  
568        Yes  
918         No  
749        Yes  
1242        No  
898         No  
956         No

In [181]:
df['DistanceFromHome'].mean()

9.19251700680272

In [182]:
(df['Attrition']=="Yes").sum()

237

In [184]:
len(df[df['Attrition']=="Yes"])

237

In [ ]:
#groupby

In [39]:
df.groupby(["Department","JobRole"])["Age"].mean().to_frame()

Age
Department             JobRole                             
Human Resources        Human Resources            35.500000
                       Manager                    48.727273
Research & Development Healthcare Representative  39.809160
                       Laboratory Technician      34.096525
                       Manager                    45.962963
                       Manufacturing Director     38.296552
                       Research Director          44.000000
                       Research Scientist         34.236301
Sales                  Manager                    47.351351
                       Sales Executive            36.889571
                       Sales Representative       30.361446

In [193]:
df.groupby(["Department"])[["Age","MonthlyIncome"]].mean()

Age  MonthlyIncome
Department                                      
Human Resources         37.809524    6654.507937
Research & Development  37.042664    6281.252862
Sales                   36.542601    6959.172646

In [200]:
df.groupby(["Department"])["Age"].agg(['mean','min','max'])

mean  min  max
Department                                 
Human Resources         37.809524   19   59
Research & Development  37.042664   18   60
Sales                   36.542601   18   60

In [202]:
df.groupby(["Department"])[["Age","MonthlyIncome"]].agg({'Age':'mean','MonthlyIncome':'sum'})

Age  MonthlyIncome
Department                                      
Human Resources         37.809524         419234
Research & Development  37.042664        6036284
Sales                   36.542601        3103791

In [ ]:
#Pivot table

In [205]:
pd.pivot_table(df,index=["Department"],values=["Age","MonthlyIncome"], aggfunc={'Age':'mean','MonthlyIncome':'sum'})

Age  MonthlyIncome
Department                                      
Human Resources         37.809524         419234
Research & Development  37.042664        6036284
Sales                   36.542601        3103791

In [42]:
df.head(2)

S.No.  Gender              Department             JobRole MaritalStatus  \
0      1  Female                   Sales     Sales Executive        Single   
1      2    Male  Research & Development  Research Scientist       Married   

   JobSatisfaction  HourlyRate  MonthlyIncome  PercentSalaryHike  \
0                4        94.0           5993                 11   
1                2        61.0           5130                 23   

   PerformanceRating  TotalWorkingYears  EnvironmentRating  YearsAtCompany  \
0                3.0                  8                  1               6   
1                4.0                 10                  3              10   

   YearsInCurrentRole  Age  DistanceFromHome  YearsWithCurrManager Attrition  
0                   4   41                 1                     5       Yes  
1                   7   49                 8                     7        No

In [40]:
df.iloc[:,0:3]

S.No.  Gender              Department
0         1  Female                   Sales
1         2    Male  Research & Development
2         4    Male  Research & Development
3         5  Female  Research & Development
4         7    Male  Research & Development
...     ...     ...                     ...
1465   2061    Male  Research & Development
1466   2062    Male  Research & Development
1467   2064    Male  Research & Development
1468   2065    Male                   Sales
1469   2068    Male  Research & Development

[1470 rows x 3 columns]

In [41]:
df.loc[:,['S.No.','Gender']]

S.No.  Gender
0         1  Female
1         2    Male
2         4    Male
3         5  Female
4         7    Male
...     ...     ...
1465   2061    Male
1466   2062    Male
1467   2064    Male
1468   2065    Male
1469   2068    Male

[1470 rows x 2 columns]

In [213]:
first_100=df.head(100)
remaining=df.iloc[100:,:]

In [215]:
df_new=pd.concat([remaining,first_100],axis=0)

In [216]:
df_new

S.No.  Gender              Department                    JobRole  \
100    133    Male         Human Resources            Human Resources   
101    134    Male  Research & Development         Research Scientist   
102    137  Female  Research & Development      Laboratory Technician   
103    138  Female  Research & Development         Research Scientist   
104    139    Male  Research & Development  Healthcare Representative   
..     ...     ...                     ...                        ...   
95     126  Female  Research & Development          Research Director   
96     128  Female                   Sales            Sales Executive   
97     129    Male                   Sales            Sales Executive   
98     131    Male                   Sales            Sales Executive   
99     132    Male  Research & Development      Laboratory Technician   

    MaritalStatus  JobSatisfaction  HourlyRate  MonthlyIncome  \
100      Divorced                1        63.0           2073   
101        Single                1        71.0           2956   
102        Single                4        66.0           2926   
103        Single                3        41.0           4809   
104      Divorced                4       100.0           5163   
..            ...              ...         ...            ...   
95        Married                3        60.0          13549   
96        Married                3        33.0           4999   
97        Married                3        43.0           4221   
98         Single                3        37.0          13872   
99        Married                2        67.0           2042   

     PercentSalaryHike  PerformanceRating  TotalWorkingYears  \
100                 22                4.0                  7   
101                 13                3.0                  1   
102                 18                3.0                  1   
103                 14                3.0                 16   
104                 14                3.0                 17   
..                 ...                ...                ...   
95                  12                3.0                 16   
96                  21                4.0                  4   
97                  15                3.0                  5   
98                  13                3.0                 38   
99                  12                3.0                 17   

     EnvironmentRating  YearsAtCompany  YearsInCurrentRole  Age  \
100                  3               3                   2   37   
101                  3               1                   0   32   
102                  3               1                   0   20   
103                  3              16                  13   34   
104                  4               1                   0   37   
..                 ...             ...                 ...  ...   
95                   1               4                   3   54   
96                   2               3                   2   24   
97                   4               5                   4   28   
98                   2              37                  10   58   
99                   4               3                   2   44   

     DistanceFromHome  YearsWithCurrManager Attrition  
100                 6                     2       Yes  
101                 1                     0        No  
102                 6                     0       Yes  
103                 6                    10        No  
104                 2                     0        No  
..                ...                   ...       ...  
95                  2                     3        No  
96                  3                     2        No  
97                  4                     4        No  
98                 10                     8        No  
99                 23                     2        No  

[1470 rows x 18 columns]

In [224]:
s1={'subject':['english','maths','science'],
'marks':[68,75,84]}

s2={'subject':['tamil','maths','science','Arts'],
'marks':[61,78,81,89]}


In [225]:
df2=pd.DataFrame(s1)
df3=pd.DataFrame(s2)

In [228]:
df2

subject  marks
0  english     68
1    maths     75
2  science     84

In [229]:
df3

subject  marks
0    tamil     61
1    maths     78
2  science     81
3     Arts     89

In [230]:
df2.merge(df3,on='subject',how="inner")

subject  marks_x  marks_y
0    maths       75       78
1  science       84       81

In [232]:
df2.merge(df3,on='subject',how="left")

subject  marks_x  marks_y
0  english       68      NaN
1    maths       75     78.0
2  science       84     81.0

In [233]:
df2.merge(df3,on='subject',how="right")

subject  marks_x  marks_y
0    tamil      NaN       61
1    maths     75.0       78
2  science     84.0       81
3     Arts      NaN       89

In [234]:
df2.merge(df3,on='subject',how="outer")

subject  marks_x  marks_y
0  english     68.0      NaN
1    maths     75.0     78.0
2  science     84.0     81.0
3    tamil      NaN     61.0
4     Arts      NaN     89.0

In [235]:
df2.merge(df3,how="cross")

subject_x  marks_x subject_y  marks_y
0    english       68     tamil       61
1    english       68     maths       78
2    english       68   science       81
3    english       68      Arts       89
4      maths       75     tamil       61
5      maths       75     maths       78
6      maths       75   science       81
7      maths       75      Arts       89
8    science       84     tamil       61
9    science       84     maths       78
10   science       84   science       81
11   science       84      Arts       89

In [238]:
df1.merge(df1,left_on= 'subject',right_on= "subject",how='inner')

subject  marks_x  marks_y
0  english       80       80
1    maths       75       75
2  science       91       91
3     Arts       84       84

In [243]:
df1

subject  marks
0  english     80
1    maths     75
2  science     91
3     Arts     84

In [246]:
df1.drop(0)#row wise

subject  marks
1    maths     75
2  science     91
3     Arts     84

In [247]:
df2.drop('subject',axis=1)#column wise

marks
0     68
1     75
2     84