In [1]:
import numpy as np
import pandas as pd

In [3]:
arr1=np.array(20)
print(arr1)

20


In [4]:
arr4=np.arange(1,50,2)  #arrange accepts float value
print(arr4)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [8]:
arr5=np.zeros(4,dtype=int)
arr5_1=np.ones(5)
print(arr5)
print(arr5_1)

[0 0 0 0]
[1. 1. 1. 1. 1.]


In [11]:
arr6=np.zeros((4,3),dtype=int)
print(arr6)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
arr7=np.random.randint(1,11,4).reshape(2,2)
print(arr7)

[[7 8]
 [2 1]]


In [31]:
a=np.zeros((4,2),dtype=int)
b=np.ones((2,2),dtype=int)
print(a)
print(b)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]]


In [32]:
np_2d_array = np.array([[90, 80, 67, 89, 78],
                       [11, 22, 54, 67, 98],
                       [91, 87, 65, 45, 72]])
print(np_2d_array)

[[90 80 67 89 78]
 [11 22 54 67 98]
 [91 87 65 45 72]]


In [35]:
b=np.array([1,2,3,4,5])
b[b%2!=0]=2
b

array([2, 2, 2, 4, 2])

In [39]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
b = [[1, 5, 7], [1,7, 4], [10, 18, 17]]
arrr1=np.array(A)
arrr2=np.array(b)
print(arrr1.sum(axis=1))#to calculate only column
print(arrr2.sum(axis=0))#to calculate only row

[13 15 25]
[12 30 28]
