# Lambda function using filter(no of elements in input may differ in o/p)

In [3]:
li=[1,8,7,4,3,6,5,9]
l1=list(filter(lambda x:x%2!=0,li))
print(l1)

[1, 7, 3, 5, 9]


In [7]:
#Remove odd numbers from the given list.
numbers = [21, 23, 443, 355, 743, 823, 110, 1241, 3673, 352, 278, 37, 7]
l2=list(filter(lambda x:x%2==0,numbers))
print(l2)

[110, 352, 278]


In [12]:
#Find the common elements from the given array using filter method.
arr1 = ['t','u','t','o','r','i','a','l']

arr2 = ['p','o','i','n','t']

l3=list(filter(lambda x:x in arr2,arr1))
print(l3)

['t', 't', 'o', 'i']


In [21]:
s1="praneshpsrinivAsu"
l_1=list(s1)
#print(l_1)
l2=list(filter(lambda x:x not in "aeiouAEIOU",l_1))
print(l2)

['p', 'r', 'n', 's', 'h', 'p', 's', 'r', 'n', 'v', 's']


# Lambda function using filter(Gives only one value in output)

In [26]:
l4=[1,8,7,4,13,12,4,19]
from functools import reduce  #importing reduce function from functools(because
#reduce function is not inbuilt finction)
max_value=reduce(lambda x,y:x if x>y else y,l4)
print(max_value)

19


In [28]:
l4=[1,8,7,4,13,12,4,19]
from functools import reduce 
min_value=reduce(lambda x,y:x if x<y else y,l4)
print(min_value)

1


In [32]:
l4=[1,8,7,4,13,12,4,19]
from functools import reduce  
Total_value=reduce(lambda x,y:x+y,l4)
print(Total_value)

68


In [41]:
#Calculate the sum of the numbers from 1 to 100. (make use of reduce function from functools library)
l5=[i for i in range(1,101)]
from functools import reduce 
sum=reduce(lambda x,y:x+y,l5)
print(sum)

5050


In [255]:
#Find the number closet to 100 from given list
l5=[108,114,96,89,103,94,98]
from functools import reduce
#Closer_number=reduce(lambda x,y:x if (x>y and x<100) else y ,l5)
Closer_number=reduce(lambda x,y:x if (x-100)**(2)<(y-100)**2 else y ,l5)
print(Closer_number)

98


# Some more examples on lampda functions

In [3]:
l1=[-1,2,4,2,-5,3,2,-2]
L1=list(filter(lambda x:x>=0,l1))  #To remove all negative numbers
L2=list(filter(lambda x:x!=2,l1))  #To remove all positive 2's
L3=list(map(lambda x:x*11,l1))  #To multiply all values by 11 in the list
print(L1)
print(L2)
print(L3)

[2, 4, 2, 3, 2]
[-1, 4, -5, 3, -2]
[-11, 22, 44, 22, -55, 33, 22, -22]


In [34]:
l2=[4,8,7,3,6]
l3=[12,4,2,56,8]
L4=list(map(lambda x,y:x+y,l2,l3))  #adding 2 lists
L5=list(map(lambda x,y:x-y,l2,l3))  #subtracting 2 lists
print(L4)
print(L5)

[16, 12, 9, 59, 14]
[-8, 4, 5, -53, -2]


In [11]:
list_1=[29,112,47,129,221,151]
from functools import reduce
Closer_number=reduce(lambda x,y:x if min(x%25,25-x%25)< min(y%25,25-y%25) else y ,list_1)
print(Closer_number)   #number closure to multiple of 25


151


# Arrays using NumPy

In [58]:
#Create a 0D Numpy Arrays using np.array() and prirnt the array, its type and dimension
import numpy as np  #importing the numpy
arr=np.array(54)
print("shape",arr.shape)
print("Dimension",arr.ndim)
print("type",type(arr))

shape ()
Dimension 0
type <class 'numpy.ndarray'>


In [66]:
#Create a 1-D array and print the array, it's type and dimension
arr1=np.array([1,2,3,4])
print("shape",arr.shape)
print("Dimension",arr1.ndim)
print("type",type(arr1))


shape ()
Dimension 1
type <class 'numpy.ndarray'>


In [75]:
#Create a 2-D array and print the array, it's type and dimension
arr2=np.array([[1,2,3,4],[3,4,5,8]])
print("shape",arr.shape)
print("Dimension",arr2.ndim)
print("type",type(arr2))


shape ()
Dimension 2
type <class 'numpy.ndarray'>


In [76]:
#Create a 3-D array and print the array, it's type and dimension
arr3=np.array([[[1]]])
print("shape",arr.shape)
print("Dimension",arr3.ndim)
print("type",type(arr3))


shape ()
Dimension 3
type <class 'numpy.ndarray'>


In [79]:
#Create an array from 1 to 10 with a step of 2 having float data type
arr4=np.arange(1,10,2.0)  #arrange accepts float value
print(arr4)

[1. 3. 5. 7. 9.]


In [84]:
#Create a 1D array with 4 zeros in it
arr5=np.zeros(4,dtype=int)
arr5_1=np.ones(4,dtype=int)
print(arr5)
print(arr5_1)

[0 0 0 0]
[1 1 1 1]


In [86]:
#Create 2-D array with zeros as the values in it in 4 rows and 2 columns
arr6=np.zeros((4,2))
print(arr6)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [88]:
#Create a random 2 by 2 matrix with random values from 1 to 10 
arr7=np.random.randint(1,11,4).reshape(2,2)
print(arr7)

[[9 3]
 [8 7]]


# Use of indexing in array

In [90]:
 #Print the second and fifth element of the given array.
np_array = np.array([22, 67, 90, 75, 56, 12])
print(np_array[1],np_array[4])


67 56


In [92]:
#Print the element in the second row fourth column.
np_2d_array = np.array([[90, 80, 67, 89, 78],
                       [11, 22, 54, 67, 98],
                       [91, 87, 65, 45, 72]])
print(np_2d_array[1,3])

67


In [94]:
# Print all the elements of fifth column.
np_2d_array = np.array([[90, 80, 67, 89, 78],
                       [11, 22, 54, 67, 98],
                       [91, 87, 65, 45, 72]])
print(np_2d_array[:,4])

[78 98 72]


# slicing of array

In [96]:
#Print the First, second, and third element from the given array.
np_array = np.array([22, 67, 90, 75, 56, 12])   
print(np_array[0:3])

[22 67 90]


In [101]:
#Print all the rows expect last row, and only print first three columns.
np_2d_array = np.array([[90, 80, 67, 89, 78],
                       [11, 22, 54, 67, 98],
                       [91, 87, 65, 45, 72]])
print(np_2d_array[0:2,0:3])

[[90 80 67]
 [11 22 54]]


# Operations in array

In [104]:
#Perform addition and substraction of two arrays and print the output.
np_array1 = np.array([100, 200, 300, 400, 500])

np_array2 = np.array([80, 70, 190, 290, 120])
print("addition",np_array1+np_array2)
print("subtraction",np_array1-np_array2)

addition [180 270 490 690 620]
subtraction [ 20 130 110 110 380]


In [106]:
# Print the Square of each element of the array.
np_array = np.array([22, 67, 90, 75, 56, 12])
print("Square",np_array**2)

Square [ 484 4489 8100 5625 3136  144]


In [110]:
# Print all the elements which are greater than 50.
np_array = np.array([22, 67, 90, 75, 56, 12])
print("elements are",np_array[np_array>50])


elements are [67 90 75 56]


# Arthametic functions

In [115]:
# Replace all odd numbers in array with -2.
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[arr%2!=0]=-2 #replacing the odd values by -2
print(arr)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


In [117]:
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[:1]=1
print(arr)

[ 1 31 42 43 34 45 26 27 38 94 65 78 76]


In [120]:
#Write a program to calculate the sum of each column.
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arrr1=np.array(A)
print(arrr1.sum(axis=1))#to calculate only column
print(arrr1.sum(axis=0))#to calculate only row

[13 15 25]
[15 25 13]


In [122]:
# Write a code to get the element-wise remainder of an array after division by 8
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
arrr2=np.array(num)
print(arrr2%8)

[2 7 2 6 0 3 5 0 4]


# Some more examples in array

In [217]:
a1=np.ones(9,dtype=int)
a1[::3]=0
print(a1)

[0 1 1 0 1 1 0 1 1]


In [155]:
a2=np.zeros((4,3),dtype=int)

print(a2)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [169]:
a3=np.arange(1,20,2)
print(a3)

[ 1  3  5  7  9 11 13 15 17 19]


In [221]:
a4=np.arange(1,10).reshape(3,3)
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [223]:
a5=np.zeros((3,3),dtype=int)
a5[:,0]=1
print(a5.reshape(3,3))


[[1 0 0]
 [1 0 0]
 [1 0 0]]


In [208]:
a6=np.arange(1,6)
#a6=np.arange(0.1,0.6,0.1)
print(a6/10)

[0.1 0.2 0.3 0.4 0.5]


In [226]:
a7=np.zeros((2,3),dtype=bool)
a7[0,2]=True
print(a7)

[[False False  True]
 [False False False]]


In [231]:
# Write a code to multiply two arrays
arr1 = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arr2 = np.arange(9).reshape(3,-1)
#print(arr1)
#print(arr2)
#print(arr1*arr2)
print(np.dot(arr1,arr2))
#print(np.multiply(arr1,arr2))-->same as *
# print(np.matmul(arr1,arr2))-->same as dot

[[ 60  73  86]
 [ 39  54  69]
 [ 54  79 104]]


In [233]:
#Perform addition and subtraction using arr1 and arr2. (use the arrays from previous question)
arr1 = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
arr2 = np.arange(9).reshape(3,-1)
print(arr1+arr2)
print(arr1-arr2)

[[ 1  5 10]
 [ 8 11  8]
 [15 21 10]]
[[ 1  3  6]
 [ 2  3 -2]
 [ 3  7 -6]]


In [254]:
#Find the max and min numbers in the given array
arr = np.random.randint(0, 100, 5)
arr1 = np.random.rand(5)  # random of float values
arr2 = np.random.choice([1,3,4,5,5],5)
arr3 = np.random.choice([1,3,4,5,5],3,replace=False)#not to repeat values

print(arr)
print(arr1)
print(arr2)
print(arr3)

print(arr.max())
print(min(arr))



[99 49 36 27 37]
[0.87402517 0.83220969 0.47281663 0.86376432 0.70425619]
[1 5 3 4 4]
[1 5 3]
99
27
