# Week-2-->Revision

# Functions

In [1]:
#Write a Python function to multiply all the numbers in a list.
def mul(list):
    output=1
    for i in list:
        output=output*i
    return output
li=[1,4,8,7,3]
print(mul(li))



672


In [27]:
#Write a Python function to reverse a string 
# i) use for loop
# ii) use while loop 

'''def for_loop(str):
    output=""
    for i in str:
        
        
for_loop("pranesh")'''

def while_loop(s2):
    output=""
    i=0
    while i<len(s2):
        output=s1[i]+output
        i=i+1
    return output
while_loop

    

    
    
    
    

IndentationError: expected an indented block after 'for' statement on line 7 (1092754203.py, line 9)

In [19]:
#Write a function to add and subtract two variables
def add_subtract(n1,n2):
    print("add:",n1+n2)
    print("subtract:",n1-n2)
    return add_subtract
add_subtract(30,20)
    

add: 50
subtract: 10


<function __main__.add_subtract(n1, n2)>

In [88]:
#Write a function to check whether the given number is divisible by 12 or not
def divisible_by_12(num):
    if(num%12==0):
        print("number divisible by 12")
    else:
        print("not divisible by 12")
    return num%2==0
divisible_by_12(72)
divisible_by_12(62)

number divisible by 12
not divisible by 12


True

In [60]:
#Write a function to calculate the number of days and weeks given the number of months
def day_week(month):
    print("no of days:",month*30)
    print("no of weeks:",month*4)
day_week(5)


no of days: 150
no of weeks: 20


In [106]:
#Write a Python function to calculate the factorial of a given argument?
def factorial(number):
    fact=1
    for i in range(1,number+1):
        fact=fact*i
    return fact
print(factorial(5))

'''by list comphrension
num=6
l1=[i for i in range(1,num+1)]
print(l1)'''

#By using recursion function



120
[1, 2, 3, 4, 5, 6]


In [82]:
#Write a Python function to find the unique elements from the list
l1=[1, 2, 3, 3, 3, 3, 4, 5, 4, 2, 4, 2, 4, 4, 2, 4, 5, 4, 34, 654, 5, 7, 6, 5, 4, 3]
def unique(numbers):
        s1=set(l1)
        l2=list(s1)
        print(l2)
unique(l1)


[1, 2, 3, 4, 5, 34, 7, 6, 654]


In [86]:
#Required arguments: - Write a function to calculate Simple Interest which accepts three arguments and returns the simple interest accordingly
def simple_intrest(principle,intrest,time):
    SI=(principle*intrest*time)/100
    print("The simple interest is :",SI)
    return SI
simple_intrest(35000,2.5,3)

The simple interest is : 2625.0


2625.0

In [149]:
#Keyword arguments: - Write a function which accepts arguments as keyword arguments. The two arguments are are **name** and **message.** Expected output is "printing the message with 'name' and  'message'"
def keyword_argument(name,message):
    print(name,message)
    
keyword_argument(name="pranesh",message=",how are you?")


pranesh ,how are you?


In [99]:
#Default Arguments: - Write a function which will accept first argument **name** as a keyword argument and age as the default argument. Expected output is "My name is 'name' and age is '75'"
def default_argument(name,age=23):
    print("my name is ",name+ " and my age is ",age)
default_argument("Pranesh")


my name is  Pranesh and my age is  23


# Lambda Function

In [124]:
#Get a number as an input from a user, identify whether it is odd or even? Print the message "odd" or "even" accordingly.
odd_even=lambda x:'even' if x%2==0 else 'odd'
num=(int(input("enter the value")))
print(odd_even(num))

enter the value25
odd


In [128]:
#Accept an input from user and square it
square=lambda x:x**2
nu1=(int(input("enter the number:")))
print(square(nu1))

enter the number:4
16


In [152]:
#Using logical operators, write a function that accepts an input from a user. If the input is between 0 and 10 print **True** otherwise print **False** 
op=lambda x:x>0 and x<10 
num2=(int(input("enter the number:")))
print(op(num2))


enter the number:25
False


In [137]:
#Accept an integer input from a user, add 5 to it and print it back?
add=lambda x:x+5
num3=(int(input("enter the number:")))
print(add(num3))

enter the number:4
9


# MAP

In [139]:
#Add the following two lists using map() 
l1=[12,24,36]
l2=[41,54,69]
add1=list(map(lambda x,y:x+y,l1,l2))
print(add1)

[53, 78, 105]


In [141]:
# Use Lambda and map functions to square each element in the given list

l3=[1, 2, 3, 4, 5, 6, 7]
square_num=list(map(lambda x:x**2,l3))
print(square_num)


[1, 4, 9, 16, 25, 36, 49]


In [143]:
#From the given list, using map function, identify odd and even numbers  
l4=[1, 2, 3, 4, 5, 6, 7]
ev_od=list(map(lambda x:"even" if x%2==0 else "odd",l4))
print(ev_od)


['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd']


In [145]:
#From the given list below, perform the Floor division using 7 on each elements of the list  
l5=[11, 12, 13, 14, 435, 6, 27]
floor_div=list(map(lambda x:x//7,l5))
print(floor_div)

[1, 1, 1, 2, 62, 0, 3]


# FILTER

In [147]:
#Using the given list filter the numbers which are not divisible by 2  
l_1=[3,12, 24, 36,43,654,65432,2,654,455,43,543]
divisible_2=list(filter(lambda x:x%2==1,l_1))
print(divisible_2)

[3, 43, 455, 43, 543]


In [150]:
#For a given list filter the even numbers.  
l_2=[1, 2, 3, 4, 5, 6]
even_num=list(filter(lambda x:x%2==0,l_2))
print(even_num)

[2, 4, 6]


In [190]:
#For a given list  filter the even numbers using a user defined function.
l_3=[2,3,5,3,6,3,7,4,6,7]
def even(list_1):
    if (list_1)%2==0:
        return True
    else:
        return False
Even_value=list(filter(even(l_3)))
print(Even_value)
    
    


TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [158]:
#For a given list filter the odd numbers using a user defined function.
l_4=[1, 12, 31, 4, 15, 6, 7]
def odd(list2):
    
    return x%2!=0
list(filter x,y:)


[1, 31, 15, 7]


# REDUCE

In [162]:
#Multiply all the elements of a list.  
L1=[1, 2, 3, 4]
from functools import reduce 
mul=reduce(lambda x,y:x*y,L1)
print(mul)

24


In [164]:
#Add all the elements of the list given below (use reduce function)   
L2=[11, 13, 15, 16, 2, 43]
add=reduce(lambda x,y:x+y,L2)
print(add)

100


In [167]:
#Find the maximum value in the list   
L3=[543, 7, 6, 4567, 7, 78, 6, 6, 78, 765, 678]
max=reduce(lambda x,y:x if x>y else y,L3)
print(max)

4567


In [177]:
#Find the minimum value in the list   
L5=[543, 7, 6, 4567, 7, 78, 6, 6, 78, 765, 678]
min=reduce(lambda x,y:x if x<y else y,L5)
print(min)


6


# Numpy

In [192]:
#Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array
import numpy as np 
l1=[1,2,3,4,5]
arr=np.array(l1)
print(arr)

[1 2 3 4 5]


In [242]:
#2. Write a program to add a new column ([[5,7]]) at the last position in the array given below

arr_1 = [[3, 4], [8, 2],[5, 9]]
arr_2=([[5,7]])
arr_1=np.array(arr_1)
arr_2=np.array(arr_2)
arr_3=np.append(arr_1,arr_2,axis=0)
print(arr_3)
#np.concatenate(arr_1,arr1_2)-->works only when dimensions are same


[[3 4]
 [8 2]
 [5 9]
 [5 7]]


In [249]:
#Create an array of integers from 20 to 2 with a step of -2
arr=np.arange(20,1,-2)
print(arr)

[20 18 16 14 12 10  8  6  4  2]


In [260]:
# Create a 2D Numpy array from list of lists

l1=[[110, 102, 183], [140, 175, 106], [170, 195, 117], [192, 140, 195]]
arr1=np.array(l1)
print(arr1)
print("dim:",arr1.ndim)
print("shape",arr1.shape)

[[110 102 183]
 [140 175 106]
 [170 195 117]
 [192 140 195]]
dim: 2
shape (4, 3)


In [265]:
#Find the minimum value along each of the rows
min=np.min(arr1,axis=1)
print(min)

[102 106 117 140]


In [269]:
# Replace all odd numbers in the array with -2
num_array_1 = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
num_array_1[num_array_1%2==1]=-2
print(num_array_1)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


In [280]:
#Stack two arrays vertically
quantity1 = np.arange(10).reshape(2,-1)
quantity2 = np.repeat(1, 10).reshape(2,-1)
print(quantity1.shape)
print(quantity2.shape)
print(np.concatenate([quantity1,quantity2],axis=0))

(2, 5)
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [283]:
#Get common elements from the two arrays
age_a = np.array([11,12,13,22,23,44,43,24,45,36])
age_b = np.array([17,22,13,22,47,34,39,44,29,28])
print(np.intersect1d(age_a,age_b))

[13 22 44]


In [286]:
#Remove all the elements from num_array1 that are present in num_array2
num_array1 = np.array([1,2,3,4,5])
num_array2 = np.array([5,6,7,8,9])
print(np.setdiff1d(num_array1,num_array2))


[1 2 3 4]


In [3]:
#Get the positions where elements of two arrays match
import numpy as np 
num_array1 = np.array([1,2,3,2,3,4,3,4,5,6])
num_array2 = np.array([7,2,10,2,7,4,9,4,9,8])
Position_of_values=np.where(num_array1==num_array2)
print(Position_of_values)


(array([1, 3, 5, 7], dtype=int64),)


In [4]:
#Reverse each of the rows of the 2D array
num_array1 = np.arange(16).reshape(4,4)
print(num_array1)
reverse=np.fliplr(num_array1)
print(reverse)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [3]:
#Swap row 1 and row 2 in the given array
import numpy as np
num_array1 = np.arange(9).reshape(3,3)
print(num_array1 )
num_array1[[0,1]]=num_array1[[1,0]]
(num_array1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [5]:
#Given the array 
#1)Concatenate the arrays along the rows
#2)Concatenate the arrays along the columns

a1 = np.array([[21, 42], [63, 78],[22,55],[124,567]])
print(a1)
print(a1.shape)
a2 = np.array([[13, 45], [37, 99],[1456, 2356],[2567,45890]])
print(a2)
print(a2.shape)
print(np.concatenate([a1,a2],axis=0))
np.concatenate([a1,a2],axis=1)

[[ 21  42]
 [ 63  78]
 [ 22  55]
 [124 567]]
(4, 2)
[[   13    45]
 [   37    99]
 [ 1456  2356]
 [ 2567 45890]]
(4, 2)
[[   21    42]
 [   63    78]
 [   22    55]
 [  124   567]
 [   13    45]
 [   37    99]
 [ 1456  2356]
 [ 2567 45890]]


array([[   21,    42,    13,    45],
       [   63,    78,    37,    99],
       [   22,    55,  1456,  2356],
       [  124,   567,  2567, 45890]])

In [6]:
str='19.5'
int(float(str))#to convert to int -->first convert to float and to int

19