# Numpy_arrays(concatenation and splitting)

In [7]:
list1=list("great learning")
list1.append(5)
list1.append(True)
print(list1)

#Converting the list to array
import numpy as np
arr1=np.array(list1)
print(arr1)


['g', 'r', 'e', 'a', 't', ' ', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 5, True]
['g' 'r' 'e' 'a' 't' ' ' 'l' 'e' 'a' 'r' 'n' 'i' 'n' 'g' '5' 'True']


In [2]:
# concatenate two 1D arrays
import numpy as np
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
print(np.concatenate([array_x, array_y]))

[11 22 13 23 22 12]


In [11]:
#You can also concatenate more than two arrays at once.
array_z = np.array([23,45])
print(np.concatenate([array_x, array_y, array_z]))

[11 22 13 23 22 12 23 45]


In [13]:
# create a 2D array
my_array = np.array([[1, 2, 3],
                 [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
#by default concatenate() is along 'axis = 0'
np.concatenate([my_array, my_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [20]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'array_x'  
# consider a 2D array -- 'my_array'
np.concatenate((array_x, my_array), axis = 1)#error-dimension must be same

AxisError: axis 1 is out of bounds for array of dimension 1

In [22]:
# split the array into sub-arrays
array_x = np.arange(8) 
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [24]:
# the split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [26]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 3)   #error-->The split() function does not allow the integer (N) as number of splits, if N does not divide the array into sub-arrays of equal length 

ValueError: array split does not result in an equal division

In [29]:
#array_split():It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length

np.array_split(array_x, 3)


#We split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

In [31]:
'''
The vsplit() function is used to split an array into multiple sub-arrays vertically (row-wise).'''

my_array = np.arange(20.0).reshape(4,5)
my_array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [33]:
np.vsplit(my_array, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]),
 array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

In [35]:
#The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [37]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

# Practise excercise

In [ ]:
#Write a code to divide the array into three sub-arrays containing an equal number of rows. 
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [46]:
# Write a program to divide the array into two sub-arrays containing an equal number of columns

B =np.array([[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]])
print(B.shape)
B1,B2=np.hsplit(B,2)
print(B1)
print(B2)

(3, 4)
[[ 8  7]
 [ 2 -3]
 [ 8  5]]
[[ 0  9]
 [ 5 10]
 [-1  3]]


In [49]:
#Stack two arrays vertically
array1 = np.arange(10).reshape(2,-1)

array2 = np.repeat(1, 10).reshape(2,-1)
print(array1.shape)
print(array2.shape)
np.concatenate([array1,array2])#default axis=0

(2, 5)
(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
#Stack two arrays horizontally
array3 = np.arange(20).reshape(4,-1)

array4 = np.arange(20, 40, 1).reshape(4,-1)
print(array3.shape)
print(array4.shape)
np.concatenate([array3,array4],axis=1)


(4, 5)
(4, 5)


array([[ 0,  1,  2,  3,  4, 20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34],
       [15, 16, 17, 18, 19, 35, 36, 37, 38, 39]])

In [71]:
#Stack the arrays horizontally and vertically
array5 = np.arange(20).reshape(2,-1)

array6 = np.arange(20, 40, 1).reshape(4,-1)

#print(array5.shape)
#print(array6.shape)

#when the dimension differ
#print(array5)
#print(array6)
#First method
print(np.concatenate([array5,np.concatenate([array6,array6],axis=1)]))
#second method
array3=np.concatenate(np.hsplit(array5,2))
print(np.concatenate([array3,array6]))



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 20 21 22 23 24]
 [25 26 27 28 29 25 26 27 28 29]
 [30 31 32 33 34 30 31 32 33 34]
 [35 36 37 38 39 35 36 37 38 39]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


# Hand's on Excercise

In [78]:
#Write a program to create a 1D array having 100 random numbers between 0 to 50.

arr_1=np.random.randint(0,51,100)
print(arr_1)

[42 50 30 12 45 42 47 15 30 18 48 50 16  0 34 28 14 25  5 16 25  1  3  6
 47 11 19 28 47 31 12 35  2 30 16 28 32 11  9 46 28 44  9 14 32 28 45 22
 34  6 47  7 35 33 31 50 17 21 10 37 21  2 44 33  4 18  9 24 50 39 15 34
  1 37 29 24  8 46 36 50 47 40 10 48 29 22 45 25 43  9 48 33 17 18 48 40
 10 21 34 46]


In [80]:
#Check the size and shape of the array
print("shape",arr_1.shape)
print("Dimension",arr_1.ndim)

shape (100,)
Dimension 1


In [110]:
#Reshape the above array into 20*5 shape and check the shape and size
arr_1=np.random.randint(0,51,100).reshape(20,5)
print(arr_1)
print("shape",arr_1.shape)
print("Dimension",arr_1.ndim)

[[50 46 34 46 13]
 [11  2 25 28 29]
 [45 34  5 46  1]
 [35  8 35 47 43]
 [11 39 33 31 37]
 [35  5 32 31  0]
 [31 35 29 20  7]
 [12 10 41 22 44]
 [ 8 31 25 11 48]
 [ 0 18 34 15 15]
 [38 13 10 10 15]
 [17 21 10 29 21]
 [25 42 29 48 43]
 [36  3 21 30 49]
 [20  4 46  8 13]
 [ 2 45  2 17 31]
 [27 44 20 49  3]
 [23 45  9 43 11]
 [42 48 13 18 11]
 [37 35 44 22 17]]
shape (20, 5)
Dimension 2


In [130]:
#Replace the values less than 10 as 10.
arr_1[arr_1<10]=10
print(arr_1)

[[50 46 34 46 13]
 [11 10 25 28 29]
 [45 34 10 46 10]
 [35 10 35 47 43]
 [11 39 33 31 37]
 [35 10 32 31 10]
 [31 35 29 20 10]
 [12 10 41 22 44]
 [10 31 25 11 48]
 [10 18 34 15 15]
 [38 13 10 10 15]
 [17 21 10 29 21]
 [25 42 29 48 43]
 [36 10 21 30 49]
 [20 10 46 10 13]
 [10 45 10 17 31]
 [27 44 20 49 10]
 [23 45 10 43 11]
 [42 48 13 18 11]
 [37 35 44 22 17]]


In [112]:
#Write a code to check statistical details (min, max, mean values) of the above array
print(arr_1.max())
print(arr_1.min())
print(arr_1.mean())

50
10
26.45


# Operations in Array

In [8]:
# Write a program to find BMI of the patients whose height and weight is provided in the list given below
import numpy as np
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53]
weight_array=np.array(weights)
height_array=np.array(heights)
bmi=(weight_array//height_array)**2
print("The BMI Values are :",bmi)


The BMI Values are : [1225. 1521. 1024. 1369. 1849. 1296. 1296.]


# Arthamatic operations in array

In [132]:
#Replace all odd numbers in array with -2
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[arr%2!=0]=-2
print(arr)

[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


In [135]:
#Write a program to calculate the sum of each column
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
A=np.array(A)
print(A.sum(axis=0))

[15 25 13]


In [138]:
#Write a code to get the element-wise remainder of an array after division by 8
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
num=np.array(num)
print(num%8)

[2 7 2 6 0 3 5 0 4]


# Concatenation of array

In [142]:
#Stack two arrays vertically
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)
print(array1.shape)
print(array2.shape)
np.concatenate([array1,array2])

(2, 5)
(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Spliting of array

In [156]:
#Write a code to divide the array into three sub-arrays containing an equal number of rows
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]
A = np.array(A)
print(A.shape)
np.vsplit(A,3)

(6, 2)


[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

In [159]:
#Write a program to divide the array into two sub-arrays containing an equal number of columns
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]
B = np.array(B)
print(B.shape)
print(np.split(B,2,axis=1))
print(np.hsplit(B,2))


(3, 4)
[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]
[array([[ 8,  7],
       [ 2, -3],
       [ 8,  5]]), array([[ 0,  9],
       [ 5, 10],
       [-1,  3]])]


# Data from url

In [15]:
#Load a data from the given url as a numpy array
# load the dataset and while loading the data pass 'float' to the dtype parameter
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
import numpy as np
#to load the data from url
iris=np.genfromtxt(url,delimiter=',',dtype=float,usecols=[0,1,2,3])
names=('sepallength','sepalwidth','petallength','petalwidth')
#print(iris)

#Check the shape and first 5 rows
print("******"*10)
hape=iris[0:5]
print("shape",hape.shape)

# Write a code to extract text column "sepallength" from the imported iris array.
print("******"*10)
arr1=iris[:,0]
print(arr1)

#Write a code to normalize an array so the values range exactly between 0 and 1.
print("******"*10)
sl_max=arr1.max()
sl_min=arr1.min()
print("max and min:",sl_max,sl_min)
Normalize=(arr1-sl_min)/(sl_max-sl_min)
print(Normalize[:10])

#Find the 25th, 50th, and 75th percentile of iris's sepallength.
print("******"*10)
print(np.percentile(arr1,q=[25,50,75]))

#Insert np.nan values at 50 random positions in iris datatset.
print("******"*10)
index_nan=np.random.choice(iris.size,50,replace=False)#adding nan to the data
iris.ravel()[index_nan]=np.nan#1d array of iris data
print(np.isnan(iris).sum())

#Find the number and position of missing values in the column 'sepallength'.
print("******"*10)
print("no of missing values",np.isnan(iris[:,0]).sum())
print("Position of missing values: \n",np.where(np.isnan(iris[:,0])))#where-to find the index

#Retrieve the rows of iris that has sepallength(1st column) < 5
print("******"*10)
print(iris[iris[:,0]<5])

#Select rows that does not contain any missing values.
print("******"*10)



************************************************************
shape (5, 4)
************************************************************
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
************************************************************
max and min: 7.9 4.3
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667]
************************************************************


In [21]:
#Select rows that does not contain any missing values.
drop_na=np.array([~np.any(np.isnan(row)) for row in iris])
print(drop_na)
print(iris[drop_na])

[ True  True  True  True False  True  True  True  True  True  True False
  True  True  True False  True  True False False  True  True  True False
  True False False  True  True False  True  True  True False False  True
  True  True  True  True  True False  True False False  True False False
  True  True False False  True False False  True  True False False  True
  True  True  True  True False  True  True  True  True  True False False
  True  True  True  True False  True False  True  True  True  True  True
  True False False  True False  True  True  True  True  True  True  True
 False  True  True  True  True  True  True  True  True False  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True False  True  True False  True False  True False  True  True  True
 False False  True  True  True  True  True  True  True  True False False
  True  True  True  True False False]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.4 3.9 

In [28]:
#use of isnan and where 
a=np.array([[1,2,np.nan],[4,8,6],[2,np.nan,2]])
print(np.isnan(a)) #to verify non values
print(np.where(np.isnan(a)))#Position of non values


[[False False  True]
 [False False False]
 [False  True False]]
(array([0, 2], dtype=int64), array([2, 1], dtype=int64))


In [29]:
#use of any and all
b=np.array([0,1,5,4,6,10])
print(np.any(b%2!=0))
print(np.all(b%2!=0))
print(np.any(b>=0))

True
False
True


In [31]:
print(a.ravel()) #use of ravel
print(a)

[ 1.  2. nan  4.  8.  6.  2. nan  2.]
[[ 1.  2. nan]
 [ 4.  8.  6.]
 [ 2. nan  2.]]
